services: mongodb
language: python
python:
  - "3.5"
git:
  depth: 3
addons:
  hosts:
    - mongo
install:
  - mkdir deps
  - git clone -b https://github.com/Kobnar/stackcite.api.git deps/stackcite.api
  - cd deps/stackcite.api
  - python setup.py develop
  - ../..
  - python setup.py develop
script: nose2